
-- Adding Users:
INSERT INTO users (name, email, password) VALUES ('Tester', 'tt@mail.com', '123123');
INSERT INTO users (name, email, password) VALUES ('Gledis', 'Glediscecja41@gmail.com', 'Gledis01');
INSERT INTO users (name, email, password) VALUES ('Fjona', 'kfjona@gmail.com', 'Merrychristmas1');
INSERT INTO users (name, email, password) VALUES ('Berna', 'biem1206@gmail.com', 'Berrycherry1');
INSERT INTO users (name, email, password) VALUES ('Dilbar', 'kangarli.dilbar@gmail.com', 'Dely22');

-- Example Mood Entries for User with id 1
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-10-01', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-10-02', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-10-03', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-10-04', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-05', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-07', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-08', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-10-09', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-10', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-11', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-10-13', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-10-15', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-10-16', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-17', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-10-19', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-10-20', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-10-22', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-10-23', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-24', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-25', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-26', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-10-27', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-28', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-10-29', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-10-30', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-10-31', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-01', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-02', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-03', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-04', 'A bit tired today.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-11-05', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-11-06', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-11-07', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-08', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-11-09', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-10', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-11', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-11-12', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-13', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-14', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-15', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-16', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-17', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-11-18', 'Excited for the weekend!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-11-19', 'A bit tired today.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-11-21', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-23', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-11-24', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-11-25', 'A bit tired today.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-11-26', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-11-27', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-28', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-11-29', 'Enjoyed a nice walk.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-11-30', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 4, '2024-12-01', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-12-02', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-03', 'Feeling down, but staying positive.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-05', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-06', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-12-07', 'A calm and peaceful day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-12-08', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-09', 'Had a productive day.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-10', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 2, '2024-12-11', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-12-12', 'A bit tired today.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 5, '2024-12-13', 'Focusing on self-improvement.');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 1, '2024-12-14', 'Feeling great!');
INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (1, 3, '2024-12-15', 'A calm and peaceful day.');
--
---- Example Mood Entries for User with id 2
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-10-01', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-10-02', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-10-03', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-10-04', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-07', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-08', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-10-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-10', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-11', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-10-13', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-10-15', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-10-16', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-17', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-10-19', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-10-20', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-10-22', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-10-23', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-24', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-25', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-26', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-10-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-10-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-10-30', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-10-31', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-01', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-02', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-03', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-04', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-11-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-11-06', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-11-07', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-08', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-11-09', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-10', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-11', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-11-12', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-13', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-14', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-15', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-16', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-17', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-11-18', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-11-19', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-11-21', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-23', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-11-24', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-11-25', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-11-26', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-11-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-11-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-11-30', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 4, '2024-12-01', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-12-02', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-03', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-05', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-06', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-12-07', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-12-08', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-10', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 2, '2024-12-11', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-12-12', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 5, '2024-12-13', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 1, '2024-12-14', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (2, 3, '2024-12-15', 'A calm and peaceful day.');
--
--
---- Example Mood Entries for User with id 3
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-10-01', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-10-02', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-10-03', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-10-04', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-07', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-08', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-10-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-10', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-11', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-10-13', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-10-15', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-10-16', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-17', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-10-19', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-10-20', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-10-22', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-10-23', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-24', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-25', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-26', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-10-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-10-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-10-30', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-10-31', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-01', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-02', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-03', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-04', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-11-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-11-06', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-11-07', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-08', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-11-09', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-10', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-11', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-11-12', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-13', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-14', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-15', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-16', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-17', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-11-18', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-11-19', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-11-21', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-23', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-11-24', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-11-25', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-11-26', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-11-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-11-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-11-30', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 4, '2024-12-01', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-12-02', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-03', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-05', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-06', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-12-07', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-12-08', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-10', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 2, '2024-12-11', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-12-12', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 5, '2024-12-13', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 1, '2024-12-14', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (3, 3, '2024-12-15', 'A calm and peaceful day.');
--
--
---- Example Mood Entries for User with id 4
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-10-01', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-10-02', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-10-03', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-10-04', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-07', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-08', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-10-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-10', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-11', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-10-13', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-10-15', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-10-16', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-17', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-10-19', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-10-20', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-10-22', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-10-23', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-24', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-25', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-26', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-10-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-10-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-10-30', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-10-31', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-01', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-02', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-03', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-04', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-11-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-11-06', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-11-07', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-08', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-11-09', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-10', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-11', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-11-12', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-13', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-14', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-15', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-16', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-17', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-11-18', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-11-19', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-11-21', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-23', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-11-24', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-11-25', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-11-26', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-11-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-11-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-11-30', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 4, '2024-12-01', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-12-02', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-03', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-05', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-06', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-12-07', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-12-08', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-10', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 2, '2024-12-11', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-12-12', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 5, '2024-12-13', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 1, '2024-12-14', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (4, 3, '2024-12-15', 'A calm and peaceful day.');
--
---- Example Mood Entries for User with id 5
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-10-01', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-10-02', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-10-03', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-10-04', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-07', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-08', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-10-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-10', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-11', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-10-13', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-10-15', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-10-16', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-17', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-10-19', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-10-20', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-10-22', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-10-23', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-24', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-25', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-26', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-10-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-10-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-10-30', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-10-31', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-01', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-02', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-03', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-04', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-11-05', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-11-06', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-11-07', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-08', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-11-09', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-10', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-11', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-11-12', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-13', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-14', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-15', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-16', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-17', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-11-18', 'Excited for the weekend!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-11-19', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-11-21', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-23', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-11-24', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-11-25', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-11-26', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-11-27', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-28', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-11-29', 'Enjoyed a nice walk.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-11-30', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 4, '2024-12-01', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-12-02', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-03', 'Feeling down, but staying positive.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-05', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-06', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-12-07', 'A calm and peaceful day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-12-08', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-09', 'Had a productive day.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-10', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 2, '2024-12-11', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-12-12', 'A bit tired today.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 5, '2024-12-13', 'Focusing on self-improvement.');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 1, '2024-12-14', 'Feeling great!');
--INSERT INTO mood_entries (user_id, mood_id, date, note) VALUES (5, 3, '2024-12-15', 'A calm and peaceful day.');
--
--
